### ISSUE TITLE
Javascript API improvements

### ISSUE THREAD

**Issue by robert-chiniquy** [vulcand/vulcan#25]
I was thinking a more modular, hook-based JS API might be nice. Additionally it would be best to use a CommonJS module style.

There's synchronous IO here despite concerns (we invented a `vulcan.http` module).
### Conceptual request phases (which can be applied in arbitrary order)
- Request transformer
- Rate limits
- Identity
- Authorization
- Handler

To enable short and clear code, we have helper functions which take a function and return an opaque middleware object (or function) which can be passed back to Vulcan in `vulcan.order()`.
#### helper functions
- `vulcan.transform`: the user implements a function that returns a request object
- `vulcan.rate_limit`: the user implements a function that returns a structured object mapping keys to the limits
- `vulcan.identity`: the user implements a function that returns a boolean
- `vulcan.reverse_proxy`: the user implements a function that returns an array of URLs

In `vulcan.order` the user implements a function that returns an array of helper function return values.
### basic complex example

``` javascript
var v = require('vulcan');

var transformer = v.transform(function(request) {
  request.tenant_id = request.uri.match(/[^\/]*\/([0-9]+)\//)[1];
  return request;
});

var rate_limiter = v.rate_limit(function(request) {
  if (request.ip === '127.0.0.1') {
    // no limits for localhost
    return {};
  }
  return {
    request.ip: {'KB/sec': 100, 'requests per sec': 1000}
  };
});

var identity = v.identity(function(request) {
  var auth_response = v.http.post(discover('/auth_endpoints'), {
    'Auth-Token': request.headers['X-Auth-Token'],
    'Tenant-ID': request.tenant_id
  });
  if (auth_response.code == 200) {
    return true;
  }
  return false;
});

var user_rate_limiter = v.rate_limit(function(request) {
  return {request.tenant_id: {'requests per day': 50000}};
});

var handler = v.reverse_proxy(function(request) {
  return ["http://localhost:5000", "http://localhost:5001"];
});

v.order(function(request) {
  return [transformer, rate_limiter, identity, user_rate_limiter, handler];
});
```
### simple Hello World example

``` javascript
var v = require('vulcan');

v.order(function(request) {
  return [v.reverse_proxy(function(request) {
    return ["http://localhost:5000", "http://localhost:5001"];
  }];
});
```

This hello world is a little cumbersome, we can iterate, the indirection seems important right now.

**Comment by pquerna** [comment]
Alternative to reduce hello world:
- Rename `vulcan.order` to `vulcan.execute`.
- Return signature for the callback to `vulcan.execute`  changes to `<Middleware>|<Array<Middleware>>`.  So if you only have one action to take, you can return it without the array wrapper.
- `vulcan.reverse_proxy` (and all other helpers) would be changed to have two calling conventions:  The new convention is to pass in the `request` object, and then what would of been the return value of the function.  The old convention of taking a callback function is still supported.

## Example using this new API:

``` javascript
var v = require('vulcan');

v.execute(function(request) {
   return v.reverse_proxy(request, ["http://localhost:5000", "http://localhost:5001"])
});
```

## The above is identical functionally to the bellow:

``` javascript
var v = require('vulcan');

var rp = v.reverse_proxy(function(request) {
             return ["http://localhost:5000", "http://localhost:5001"]
   });

v.execute(function(request) {
   return [rp]
});
```

**Comment by robert-chiniquy** [comment]
While we're at it, the `vulcan` module object could also be a function, so your simplified API example could as easily be:

``` javascript
var v = require('vulcan')(function(request) {
  return v.reverse_proxy(request, ["http://localhost:5000", "http://localhost:5001"]);
});
```

**Comment by russellhaering** [comment]
Why support javascript at all? What if you took #42 a step further and required that all user-supplied code be written in Go?

**Comment by klizhentas** [comment]
The idea is that JS is easy enough to provide basic json-like configuration format in simple cases, at the same time it's capable of handling more complex scenarios illustrated by Robert in this proposal.

**Comment by klizhentas** [comment]
I spent some time hacking on the configuration format to reelect the use cases you've mentioned. You can find it here:

https://gist.github.com/klizhentas/8234451

Some notes:
- I still want to go with the domain-specific declarative style as it's less verbose for the simple use cases (what is important)
- Added routing/matching by regex to the service as it's the most common use case
- Custom middlewares chaining is still possible with before and after hook functions
- I've incorporated the examples that you've mentioned into the new proposed format
- Added explicit servers definition and port bindings 

I plan on going with this style, let me know what you think!

Thanks,
Sasha

**Comment by pquerna** [comment]
My Feedback:
- It should use a [CommonJS style-Modules](http://wiki.commonjs.org/wiki/Modules/1.1), this means `require`, but it lets you build multiple files, or have a `local_settings.js` written out by a config management for example.
- I do not understand what the `before` and `after` hooks actually do -- for example, in the gist it says that they run before the request is proxied.  Do they run before or after Authentication?
- Many functions appear to take different inputs and produce different outputs.  Taking `service` as an example. It seems to be a function that:
  - If invoked with single string param, returns a Future to the service definition.
  - If invoked with a string and object, defines a service.
- Can you document the calling conventions of `http()`?  And of the fields you think the object passed to `http({...})` would have? It feels like most of the time it is just dealing with proxying, but for the TLS example it sets a port and certificates.

**Comment by klizhentas** [comment]
Hey Paul,

First of all I intentionally sent you the draft versions to get the early feedback before I start writing anything substantial, so these were mockups :-)

Here are some comments and thoughts:

> It should use a CommonJS style-Modules, this means require, but it lets you build multiple files, or have a local_settings.js written out by a config management for example.*

I think supporting require() function is totally fine for cases when users would like to implement auth function in a separate file, however I think that some functions should be injected in the global namespace by default (e.g. http, service, log etc), otherwise even simple examples will be pretty verbose. My goal is to make basic examples to look similar to static nginx/apache config files, basic configs should not require any Js knowledge from users and look simple and familiar.

> I do not understand what the before and after hooks actually do -- for example, in the gist it says that they run before the request is proxied. Do they run before or after Authentication?*

"before" hooks are executed before the request is proxied to the upstream, "after" hooks are executed after the request has been proxied to the upstream. "auth" property should probably be removed at all to avoid the confusion as it can be implemented with "before" hooks. "Before" hooks can return status objects intercepting the request, or return nothing, allowing the request to proceed.  "After" hooks will be executed once the response has been collected from the upstream. There may be some ambiguity with "After" hooks in case of streaming, but I think that in this case, body can be some special object.

> Many functions appear to take different inputs and produce different outputs. Taking service as an example. It seems to be a function that:
> If invoked with single string param, returns a Future to the service definition.
> If invoked with a string and object, defines a service.*

That's a good catch. I will rename the first call to "service" to "service_link" or get rid of it entirely to avoid confusion. 

> Can you document the calling conventions of http()? And of the fields you think the object passed to http({...}) would have? It feels like most of the time it is just dealing with proxying, but for the TLS example it sets a port and certificates.

"http" can be called multiple times to define different bind ports/interfaces as well as paths to certificates that can be loaded from the network. May be we should always require port/interface to bind to from the http endpoint to avoid confusion, so the minimal example may look like:

``` javascript
http({
   port: 80,
   interface: '0.0.0.0',
   services: ['http://localhost:5000'],
})
```

so the following properties will be required:
- port
- interface
- services

the object passed to http function may also contain the following properties:
- rate
- metrics
- hooks
- match
- tls

Let me know what you think!
Sasha

**Comment by klizhentas** [comment]
I've been collecting the feedback and seems that the best way to go is have vulcan repo to be just a http reverse proxy library with interfaces
